services:
  senior-buyer:
    image: jiuwusan/z-senior-buyer:latest
    container_name: senior-buyer
    environment:
      NODE_ENV: production
      WEIDIAN_LOGIN_INTERVAL_MS: ${WEIDIAN_LOGIN_INTERVAL_MS:-5000}
    ports:
      - '37071:37071'
      - '37072:37072'
    restart: always
    volumes:
      - ./weidian/weidian-api/database:/app/weidian/weidian-api/database
      - ./youzan/youzan-api/database:/app/youzan/youzan-api/database
      - ./logs:/app/logs
    networks:
      - wk

networks:
  wk:
    external: true
